Further linting corrections

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -30,22 +30,22 @@ variables:
   patToken: $(System.AccessToken)
 
 stages:
-# Stage 1 - Audit stage: This stage checks project dependencies for security vulnerabilities
+  # Stage 1 - Audit stage: This stage checks project dependencies for security vulnerabilities
   - stage: Audit
     displayName: Run audit activities
     condition: always()
     jobs:
-    # Job 1 - Audit: This job checks project dependencies for secuirty vulnerabilites using default dotnet command
+      # Job 1 - Audit: This job checks project dependencies for secuirty vulnerabilites using default dotnet command
       - job: Audit
         displayName: Audit project dependencies for security vulnerabilites
         steps:
-        # Step 1 - Set up .NET SDK
+          # Step 1 - Set up .NET SDK
           - task: UseDotNet@2
             displayName: Set up .NET SDK (version $(dotnetVersion))
             inputs:
               packageType: sdk
               version: $(dotnetVersion).x
-        # Step 2 - Restore NuGet packages
+          # Step 2 - Restore NuGet packages
           - task: DotNetCoreCLI@2
             displayName: Restore .NET project dependencies (NuGet)
             inputs:
@@ -53,7 +53,7 @@ stages:
               projects: "**/*.csproj"
               feedsToUse: select
               vstsFeed: $(nugetFeed)
-        # Step 3 - Check for security vulnerabilities within project dependencies
+          # Step 3 - Check for security vulnerabilities within project dependencies
           - task: Bash@3
             displayName: Scan for vulnerable NuGet packages
             inputs:
@@ -63,11 +63,11 @@ stages:
                 dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
                 echo "Analyse dotnet list package command log output..."
                 if grep -q -i "critical\|high" build.log; then
-                    echo "Must fix security vulnerabilities found on the log output."
-                    exit 1      # Fails the job if critical or high vulnerabilities are found
+                  echo "Must fix security vulnerabilities found on the log output."
+                  exit 1      # Fails the job if critical or high vulnerabilities are found
                 else
-                    echo "No critical or high severity vulnerabilities found."
-                    exit 0      # Passes the job if no critical/high vulnerabilities are found
+                  echo "No critical or high severity vulnerabilities found."
+                  exit 0      # Passes the job if no critical/high vulnerabilities are found
                 fi
 
   # Stage 2 - Test stage: This stage runs the project unit tests
@@ -76,18 +76,18 @@ stages:
     dependsOn: Audit
     condition: succeeded()
     jobs:
-    # Job 1 - Unit: Runs unit tests.
+      # Job 1 - Unit: Runs unit tests.
       - job: Unit
         displayName: Run unit tests
         dependsOn: []
         steps:
-        # Step 1 - Set up .NET SDK
+          # Step 1 - Set up .NET SDK
           - task: UseDotNet@2
             displayName: Set up .NET SDK (version $(dotnetVersion))
             inputs:
               packageType: sdk
               version: $(dotnetVersion).x
-        # Step 2 - Restore NuGet packages
+          # Step 2 - Restore NuGet packages
           - task: DotNetCoreCLI@2
             displayName: Restore .NET project dependencies (NuGet)
             inputs:
@@ -96,14 +96,14 @@ stages:
               feedsToUse: select
               vstsFeed: $(nugetFeed)
               verbosityRestore: Normal
-        # Step 3 - Build the project
+          # Step 3 - Build the project
           - task: DotNetCoreCLI@2
             displayName: Build project
             inputs:
               command: build
               projects: "**/*.csproj"
               arguments: --configuration $(buildConfiguration) --no-restore
-        # Step 4 - Run unit tests and filter by category
+          # Step 4 - Run unit tests and filter by category
           - task: DotNetCoreCLI@2
             displayName: Run unit tests
             inputs:
@@ -123,7 +123,7 @@ stages:
         displayName: Build and Push for Development
         condition: eq(variables["Build.SourceBranch"], "refs/heads/develop")
         steps:
-        # Step 1: Build the Docker image
+          # Step 1: Build the Docker image
           - task: Docker@2
             displayName: Build Docker Image
             inputs:
@@ -137,7 +137,7 @@ stages:
                 $(tag)
               arguments: |
                 --build-arg PDS_FEED_PAT=$(patToken)
-        # Step 2: Push the Docker image to the Development container registry
+          # Step 2: Push the Docker image to the Development container registry
           - task: Docker@2
             displayName: Push Docker Image to Dev Container Registry
             inputs:
@@ -152,7 +152,7 @@ stages:
         displayName: Build and Push for Pre-Production and Production
         condition: startsWith(variables["build.sourceBranch"], "refs/heads/release")
         steps:
-        # Step 1: Build the Docker image
+          # Step 1: Build the Docker image
           - task: Docker@2
             displayName: Build Docker Image
             inputs:
@@ -165,7 +165,7 @@ stages:
                 $(tag)-rc
               arguments:
                 --build-arg PDS_FEED_PAT=$(patToken)
-        # Step 2: Push the Docker image to the Preprod container registry
+          # Step 2: Push the Docker image to the Preprod container registry
           - task: Docker@2
             displayName: Push Docker Image to Preprod Container Registry
             inputs:
@@ -175,7 +175,7 @@ stages:
               tags: |
                 latest-rc
                 $(tag)-rc
-        # Step 3: Build the Docker image
+          # Step 3: Build the Docker image
           - task: Docker@2
             displayName: Build Docker Image
             inputs:
@@ -188,7 +188,7 @@ stages:
                 $(tag)-rc
               arguments:
                 --build-arg PDS_FEED_PAT=$(patToken)
-        # Step 4: Push the Docker image to the Prod container registry
+          # Step 4: Push the Docker image to the Prod container registry
           - task: Docker@2
             displayName: Push Docker Image to Prod Container Registry
             inputs:
@@ -202,13 +202,13 @@ stages:
       - job: Publish
         displayName: Publish build artifact
         steps:
-        # Step 1 - Set up .NET SDK
+          # Step 1 - Set up .NET SDK
           - task: UseDotNet@2
             displayName: Set up .NET SDK (version $(dotnetVersion))
             inputs:
               packageType: sdk
               version: $(dotnetVersion).x
-        # Step 2 - Restore NuGet packages
+          # Step 2 - Restore NuGet packages
           - task: DotNetCoreCLI@2
             displayName: Restore .NET project dependencies (NuGet)
             inputs:
@@ -217,14 +217,14 @@ stages:
               feedsToUse: select
               vstsFeed: $(nugetFeed)
               verbosityRestore: Normal
-        # Step 3 - Build the project
+          # Step 3 - Build the project
           - task: DotNetCoreCLI@2
             displayName: Build project
             inputs:
               command: build
               projects: "**/*.csproj"
               arguments: --configuration $(buildConfiguration) --no-restore
-        # Step 4 - Publish project
+          # Step 4 - Publish project
           - task: DotNetCoreCLI@2
             displayName: Publish project
             inputs:
@@ -233,14 +233,14 @@ stages:
               zipAfterPublish: true
               projects: $(publishProjectPath)
               arguments: --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build
-        # Step 5 - Copy published project to artifact directory
+          # Step 5 - Copy published project to artifact directory
           - task: CopyFiles@2
             displayName: "Copy files to: $(build.artifactstagingdirectory)"
             inputs:
               contents: |
                 azure/**
               targetFolder: $(build.artifactstagingdirectory)/publish
-        # Step 6 - Publish build artifact
+          # Step 6 - Publish build artifact
           - task: PublishBuildArtifacts@1
             displayName: Publish build artifact
             inputs:
